### PR TITLE
update to most recent deps

### PR DESCRIPTION
**Pull request by rogerroelofs**
updates to the following:
  castore 0.1.17 => 0.1.18
  esbuild 0.4.0 => 0.5.0 (minor)
  floki 0.32.1 => 0.33.1 (minor)
  gettext 0.19.1 => 0.20.0 (minor)
  httpoison 1.8.1 => 1.8.2
  jason 1.3.0 => 1.4.0
  mime 2.0.2 => 2.0.3
  phoenix 1.6.8 => 1.6.12
  phoenix_live_view 0.17.9 => 0.17.11
  plug_crypto 1.2.2 => 1.2.3
  postgrex 0.16.3 => 0.16.4
  swoosh 1.6.6 => 1.8.0

### CODE REVIEW

**Comment by falonofthetower** [comment]
@rogerroelofs do we have any standards for how to do due diligence on code reviews?

**Comment by rogerroelofs** [comment]
Not specifically. Generally I pull the PR, run the tests and fire up the app server and poke around. In this case there's nothing specific to test except "It doesn't crash"

**Review by falonofthetower — COMMENTED** [review]
I am unable to run `mix deps.get`
`** (Mix) Unknown package version phoenix 1.6.12 in lockfile`

**Comment by rogerroelofs** [comment]
@falonofthetower I've updated the README and added a .tool-versions file. If you are using asdf you should be able to `asdf install` I'm betting your elixir version is older than mine.

**Review by falonofthetower — APPROVED** [review]
LGTM

**Pull request merged**
